### ISSUE TITLE
FloodRisk2 Error

### ISSUE THREAD

**Issue by aminamn** [FloodRiskGroup/FloodRisk-doc#1]
I got an Error when I used FloodRiskData_2 to run the plugin FloodRisk2 with:
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead. 
Traceback (most recent call last):
  File "C:/Users/Amin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\floodrisk2\ProjectCalcolaRischio\ProjectCalcolaRischioDialog.py", line 419, in EseguiScenario
    NotErr, errMsg, TotalDamageDic = mainCalcolaRischio(InputList,self.progressBar)
  File "C:/Users/Amin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\floodrisk2\ProjectCalcolaRischio\CalcolaScenarioRischio.py", line 1162, in mainCalcolaRischio
    nn=len(ListaDatiInput)
  File "C:/Users/Amin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\floodrisk2\ProjectCalcolaRischio\CalcolaScenarioRischio.py", line 770, in AssessConsequencesPopulation
    mask_alt[i]=mask_alt[i]^mask_alt[j]
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

What should I do to run the plugin with FloodRiskData_2????

**Comment by FloodRiskGroup** [comment]
I have updated the plugin to overcome the problem
